# Generated by Django 4.2.9 on 2024-01-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationapp', '0003_player_tournament_name_alter_player_display_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAccessTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_token', models.TextField()),
                ('access_token', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GoogleRawLoginCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(max_length=255)),
                ('project_id', models.CharField(max_length=255)),
            ],
        ),
    ]
