# Generated by Django 4.2.9 on 2024-01-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationapp', '0004_googleaccesstokens_googlerawlogincredentials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='display_name',
        ),
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
