FROM        python:3.11.7-bullseye

RUN         apt update -y && \
            apt upgrade -y && \
            apt install python3.11.7 -y

RUN         mkdir -p /microservice/player/

RUN         pip -r install /microservice/player/requirements.txt

WORKDIR     /microservice/player/

CMD         [ "python", "manage.py", "runserver" ]