FROM        python:3.11.7-bullseye

RUN         apt update -y && \
            apt upgrade -y

RUN         mkdir -p /microservice/player/

RUN         pip install -r /microservice/player/requirements.txt

WORKDIR     /microservice/player/

RUN         [ "python", "manage.py", "migrate" ]

CMD         [ "python", "manage.py", "runserver", "0.0.0.0:8001" ]