FROM        python:3.11.7-bullseye

RUN         apt update -y && \
            apt upgrade -y && \
			apt install curl vim nano lsof -y

RUN         mkdir -p /microservice/player/

WORKDIR     /microservice/player/

CMD         [ "bash", "./tools/microservice-run.sh" ]