FROM        python:3.11.7-bullseye

RUN         apt update -y && \
            apt upgrade -y 

RUN         mkdir -p /microservice/authentication/

RUN         pip install -r /microservice/authentication/requirements.txt

WORKDIR     /microservice/authentication/

CMD         [ "python", "manage.py", "runserver" ]